backend:
  name: netlify-api
  url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: eljun/portfolio-static-template # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "assets"

collections: # A list of collections the CMS should be able to edit
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages"  # Used in the UI, ie.: "New Post"
    folder: "pages" # The path to the folder where the documents are stored
    # create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Description", name: "shortdesc", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "data"
    label: "Data"
    files:
      - name: "characters"
        label: "Porfolio"
        file: "data/characters.json"
        fields:
          - label: "Porfolio"
            name: "data"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "image", widget: "image", media_folder: "assets/img"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}

  - name: "social"
    label: "Social"
    files:
      - name: "socials"
        label: "Social"
        file: "data/socials.json"
        fields:
          - label: "Social"
            name: "social"
            widget: "list"
            fields:
              - {label: "Social Media Name", name: "name", widget: "string"}  
              - {label: "Path", name: "path", widget: "string"}  
